workflows:
  react-native-android:
    name: SAQLAIN AI Build (Bulletproof)
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables (Error Proof)
        script: |
          # Writes keys to a .env file so Vite can read them
          printf "KEY1=%s\nKEY2=%s\nKEY3=%s\nKEY4=%s\nKEY5=%s\nKEY6=%s\n" \
          "$KEY1" "$KEY2" "$KEY3" "$KEY4" "$KEY5" "$KEY6" > .env
          echo "Environment variables set successfully."

      - name: Install Dependencies (Fix for React 19)
        script: |
          # --legacy-peer-deps prevents crashes with React 19
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          # Installs the icon tool safely
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: Build Web Assets
        script: |
          # This compiles your Google AI Studio code
          npm run build

      - name: Sync Android & Handle Assets
        script: |
          # 1. Clean old Android folder to prevent caching errors
          rm -rf android
          
          # 2. Initialize fresh Android container
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          # 3. Fix Internet Permissions (Crucial for AI)
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          # 4. Generate Icon (Skips if file missing, prevents crash)
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          else
            echo "WARNING: assets/icon.png not found. Using default icon."
          fi
          
          # 5. Final Sync
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
