workflows:
  react-native-android:
    name: SAQLAIN AI APK Build
    max_build_duration: 120
    instance_type: linux
    environment:
      groups:
        - ai_credentials # This pulls in your 6 API keys
      vars:
        PACKAGE_NAME: "com.saqlainai" # Replace if your package name is different
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: | 
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
