workflows:
  android-release:
    name: SAQLAIN AI Build
    # This line tells Codemagic to go INSIDE your project folder first
    working_directory: SAQLAIN-AI 
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - ai_credentials # Make sure KEY1 to KEY6 are in this group in the UI
      vars:
        PACKAGE_NAME: "com.saqlainai"
      flutter: stable
    scripts:
      - name: Setup Environment Variables
        script: |
          echo "KEY1=$KEY1" > .env
          echo "KEY2=$KEY2" >> .env
          echo "KEY3=$KEY3" >> .env
          echo "KEY4=$KEY4" >> .env
          echo "KEY5=$KEY5" >> .env
          echo "KEY6=$KEY6" >> .env
      - name: Get dependencies
        script: |
          # FIXED: Switched from npm to flutter commands
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
