workflows:
  react-native-android:
    name: SAQLAIN AI - UNIVERSAL PERFECT FINAL
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: STEP 1 - NUCLEAR RESET
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
          export NODE_OPTIONS="--max-old-space-size=4096"
          rm -rf node_modules package-lock.json android dist build capacitor.config.json local.properties
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps

      - name: STEP 2 - UNIVERSAL JS INTERCEPTOR & MODULE STRIP
        script: |
          npm run build
          [ ! -d "dist" ] && mv build dist || true
          USER_API_KEY="$KEY1"
          cat <<EOF > interceptor.js
          <script>
          (function() {
            window.SAQLAIN_SHIELD = true;
            const KEYS = ["$USER_API_KEY", "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"];
            const oldFetch = window.fetch;
            window.fetch = async function(...args) {
              if (typeof args[0] === 'string' && args[0].includes('googleapis.com')) {
                const k = KEYS[0];
                let u = args[0].replace('gemini-pro', 'gemini-1.5-flash');
                u = u.includes('key=') ? u.replace(/key=[^&]*/, 'key='+k) : u + (u.includes('?') ? '&' : '?') + 'key=' + k;
                args[0] = u;
                args[1] = args[1] || {};
                args[1].headers = new Headers(args[1].headers || {});
                args[1].headers.delete('Origin');
                args[1].headers.delete('Referer');
              }
              return oldFetch(...args);
            };
          })();
          </script>
          EOF
          find dist -name "*.html" -exec sed -i '' -e '/<head>/r interceptor.js' {} +
          find dist -name "*.html" -exec sed -i '' 's|type="module"||g' {} +
          find dist -name "*.html" -exec sed -i '' 's|crossorigin||g' {} +
          find dist -type f \( -name ".html" -o -name ".js" \) -exec sed -i '' 's|src="/|src="./|g' {} +
          find dist -type f \( -name ".html" -o -name ".css" \) -exec sed -i '' 's|href="/|href="./|g' {} +

      - name: STEP 3 - NATIVE SYNC & ASSET GUARD
        script: |
          echo " { \"appId\": \"com.saqlainai\", \"appName\": \"SAQLAIN AI\", \"webDir\": \"dist\", \"server\": { \"androidScheme\": \"https\", \"cleartext\": true } }" > capacitor.config.json
          npx cap add android
          mkdir -p android/app/src/main/res/xml
          cat <<EOF > android/app/src/main/res/xml/network_security_config.xml
          <?xml version="1.0" encoding="utf-8"?><network-security-config><base-config cleartextTrafficPermitted="true"><trust-anchors><certificates src="system" /><certificates src="user" /></trust-anchors></base-config><domain-config cleartextTrafficPermitted="true"><domain includeSubdomains="true">localhost</domain><domain includeSubdomains="true">googleapis.com</domain></domain-config></network-security-config>
          EOF
          npx cap sync android
          cp -R dist/* android/app/src/main/assets/public/

      - name: STEP 4 - NATIVE ATOMIC STRIKE (CROSS-VERSION COMPATIBLE)
        script: |
          sleep 3
          MAIN_ACTIVITY=$(find android/app/src/main/java -name "MainActivity.java")
          sed -i '' 's/import com.getcapacitor.BridgeActivity;/import com.getcapacitor.BridgeActivity; import android.os.Bundle; import android.os.StrictMode; import android.webkit.WebSettings;/g' "$MAIN_ACTIVITY"
          cat <<EOF > patch.txt
              @Override
              public void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  try {
                      StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().permitAll().build());
                  } catch (Exception e) {}
              }
              @Override
              public void onWindowFocusChanged(boolean hasFocus) {
                  super.onWindowFocusChanged(hasFocus);
                  if (hasFocus && this.bridge != null && this.bridge.getWebView() != null) {
                      try {
                          WebSettings s = this.bridge.getWebView().getSettings();
                          s.setMixedContentMode(0); 
                          s.setDomStorageEnabled(true);
                          s.setDatabaseEnabled(true);
                      } catch (Exception e) {}
                  }
              }
          EOF
          sync
          sed -i '' '/public void onCreate(Bundle savedInstanceState)/,/}/d' "$MAIN_ACTIVITY"
          sed -i '' -e '$i\
          ' patch.txt "$MAIN_ACTIVITY"
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '' 's|<manifest|<manifest xmlns:tools="http://schemas.android.com/tools"|g' "$MANIFEST"
          sed -i '' 's|<application|<application android:usesCleartextTraffic="true" tools:node="merge" tools:replace="android:usesCleartextTraffic,android:networkSecurityConfig" android:networkSecurityConfig="@xml/network_security_config"|g' "$MANIFEST"

      - name: STEP 5 - THE CLEAN COMPILE (TOOLCHAIN LOCK)
        script: |
          export JAVA_HOME=$JAVA_HOME_17
          cd android
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon --rerun-tasks -Porg.gradle.java.home=$JAVA_HOME_17 -Pandroid.nonTransitiveRClass=false
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
