workflows:
  android-release:
    name: SAQLAIN AI Build
    instance_type: mac_mini_m1 
    max_build_duration: 60
    environment:
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      flutter: stable
    scripts:
      - name: Setup Environment Variables
        script: |
          # Creates a .env file that pulls your 6 keys from Codemagic UI
          echo "KEY1=$KEY1" > .env
          echo "KEY2=$KEY2" >> .env
          echo "KEY3=$KEY3" >> .env
          echo "KEY4=$KEY4" >> .env
          echo "KEY5=$KEY5" >> .env
          echo "KEY6=$KEY6" >> .env
      - name: Get dependencies
        script: |
          # FIXED: Changed from 'npm install' to 'flutter pub get'
          flutter pub get
      - name: Build Android APK
        script: |
          # Generates the release APK file
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
