workflows:
  react-native-android:
    name: SAQLAIN AI APK Build
    max_build_duration: 120
    instance_type: linux # FIXED: No curly braces or $ signs
    environment:
      groups:
        - ai_credentials # This pulls your KEY1 to KEY6
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Setup Environment
        script: |
          echo "KEY1=$KEY1" > .env
          echo "KEY2=$KEY2" >> .env
          echo "KEY3=$KEY3" >> .env
          echo "KEY4=$KEY4" >> .env
          echo "KEY5=$KEY5" >> .env
          echo "KEY6=$KEY6" >> .env
      - name: Build Android APK
        script: | 
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
