workflows:
  react-native-android:
    name: SAQLAIN AI - Triple Lock Final
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: TRIPLE LOCK FIX - Universal Quote Handler
        script: |
          echo "⚔️ Locating connection logic..."
          
          # 1. FIND THE FILE
          TARGET_FILE=$(grep -r --exclude-dir={node_modules,dist,android} "generativelanguage.googleapis.com" . | cut -d: -f1 | head -n 1)
          
          if [ -z "$TARGET_FILE" ]; then
             TARGET_FILE=$(grep -r --exclude-dir={node_modules,dist,android} "sendMessage" src | cut -d: -f1 | head -n 1)
          fi
          
          if [ ! -z "$TARGET_FILE" ]; then
             echo "🎯 Fixing file: $TARGET_FILE"
             
             # 2. DEFINE THE INLINE KEYS (6 Keys Randomizer)
             # This tiny code block picks a key randomly.
             INLINE_KEYS='["AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU", "AIzaSyDBdShSHEOJwV5-fAn5ABJLfKG3RLffoUo", "AIzaSyByhPkTsT2_zczOGGnHVJ2lLAhv14MNNxk", "AIzaSyDLlrOBRykDoeIF7YUBsMf1G_rOAK2n53c", "AIzaSyDbDzk2zEbJpDzLkyPC4a_z9WfMDfuYje0", "AIzaSyAWfQ9NCe1x5BDR6MDu-tQYoTauqKbMljU"][Math.floor(Math.random() * 6)]'
             
             # 3. UPGRADE MODEL (gemini-pro -> gemini-1.5-flash)
             # This fixes the "Model not found" error from your screenshot.
             sed -i '' "s/gemini-pro/gemini-1.5-flash/g" "$TARGET_FILE"
             
             # 4. APPLY TRIPLE-LOCK FIX (Handles ALL Quote Styles)
             # We try to fix Double Quotes, Single Quotes, AND Backticks separately.
             # Only the one that matches your code will activate.
             
             # Lock 1: Double Quotes ("...key=")
             sed -i '' "s|\"?key=|\"?key=\" + $INLINE_KEYS + \"\&ignore=|g" "$TARGET_FILE"
             
             # Lock 2: Single Quotes ('...key=')
             sed -i '' "s|'?key=|'?key=' + $INLINE_KEYS + '&ignore=|g" "$TARGET_FILE"
             
             # Lock 3: Backticks (`...key=${...}`)
             sed -i '' "s|?key=\${|?key=\${$INLINE_KEYS}\&ignore=\${|g" "$TARGET_FILE"

             echo "✅ Connection Secured. Quote style matched."
          else
             echo "❌ Could not find file to fix."
          fi

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync & Perfect Manifest
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          echo "📝 Writing Clean AndroidManifest.xml..."
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              
              <uses-permission android:name="android.permission.INTERNET" />
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
          
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/AppTheme"
                  android:usesCleartextTraffic="true">
                  <activity
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
                      android:name="com.saqlainai.MainActivity"
                      android:label="@string/title_activity_main"
                      android:theme="@style/AppTheme.NoActionBarLaunch"
                      android:launchMode="singleTask"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  <provider
                      android:name="androidx.core.content.FileProvider"
                      android:authorities="\${applicationId}.fileprovider"
                      android:exported="false"
                      android:grantUriPermissions="true">
                      <meta-data
                          android:name="android.support.FILE_PROVIDER_PATHS"
                          android:resource="@xml/file_paths" />
                  </provider>
              </application>
          </manifest>
          EOF
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
