workflows:
  react-native-android:
    name: SAQLAIN AI - Turbo Mode Fix
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @google/generative-ai --save --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: SCORCHED EARTH - Inject Turbo Key Rotation
        script: |
          echo "🔥 Injecting 6-Key Turbo Engine..."
          
          # The "Magic Code" - A random picker with all 6 keys
          # This replaces the single key string with logic that picks a random key every time
          TURBO_CODE='["AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU", "AIzaSyDBdShSHEOJwV5-fAn5ABJLfKG3RLffoUo", "AIzaSyByhPkTsT2_zczOGGnHVJ2lLAhv14MNNxk", "AIzaSyDLlrOBRykDoeIF7YUBsMf1G_rOAK2n53c", "AIzaSyDbDzk2zEbJpDzLkyPC4a_z9WfMDfuYje0", "AIzaSyAWfQ9NCe1x5BDR6MDu-tQYoTauqKbMljU"][Math.floor(Math.random() * 6)]'
          
          EXCLUDE_DIRS="--exclude-dir={node_modules,android,dist,.git}"

          # 1. Inject Turbo Code into Constructor
          # Replaces 'new GoogleGenerativeAI(...)' with 'new GoogleGenerativeAI([Key1, Key2...][random])'
          echo "💉 upgrading constructors to Turbo Mode..."
          grep -rl $EXCLUDE_DIRS "new GoogleGenerativeAI" . | xargs -I {} sed -i '' "s|new GoogleGenerativeAI(.*)|new GoogleGenerativeAI($TURBO_CODE)|g" "{}"

          # 2. Inject Turbo Code into Config Objects
          # Replaces 'apiKey: ...' with 'apiKey: [Key1, Key2...][random],'
          echo "💉 Upgrading config objects to Turbo Mode..."
          grep -rl $EXCLUDE_DIRS "apiKey:" . | xargs -I {} sed -i '' "s|apiKey:.*|apiKey: $TURBO_CODE,|g" "{}"
          
          # 3. Inject Turbo Code into Variables
          # Replaces 'const API_KEY = ...' with 'const API_KEY = [Key1, Key2...][random];'
          echo "💉 Upgrading constants to Turbo Mode..."
          grep -rl --include=".{js,jsx,ts,tsx}" $EXCLUDE_DIRS "const API_KEY =" . | xargs -I {} sed -i '' "s|const API_KEY = .|const API_KEY = $TURBO_CODE;|g" "{}"
          
          echo "✅ Turbo Mode Activated. All 6 keys are live."

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync Android & Icon
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          # Ensure Internet Permission
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
