workflows:
  react-native-android:
    name: SAQLAIN AI APK Build
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      # THE KEY FIX: Setting the Java version to 21
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          rm -f .env
          touch .env
          printf "KEY1=%s\nKEY2=%s\nKEY3=%s\nKEY4=%s\nKEY5=%s\nKEY6=%s\n" \
          "$KEY1" "$KEY2" "$KEY3" "$KEY4" "$KEY5" "$KEY6" > .env
          echo "Environment variables set."
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android
      - name: Build Web Assets
        script: |
          npm run build
      - name: Initialize Android Platform
        script: |
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist || true
          npx cap add android || true
          npx cap sync android
      - name: Build Android APK
        script: |
          # Ensuring the build uses the correct Java Home
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
