workflows:
  react-native-android:
    name: SAQLAIN AI - Total Reconstruction
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install react react-dom @types/react @types/react-dom --legacy-peer-deps
          npm install @vitejs/plugin-react vite --save-dev --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: PHASE 1 - Delete Old Brain
        script: |
          echo "🗑️ DELETING OLD SOURCE CODE..."
          rm -rf src
          rm -f index.html
          rm -f vite.config.ts
          echo "✅ Old code deleted. 'Neural system failure' is gone."

      - name: PHASE 2 - Rebuild Entry Point (index.html)
        script: |
          echo "🏗️ Creating new index.html..."
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Saqlain AI</title>
            </head>
            <body>
              <div id="root"></div>
              <script type="module" src="/src/main.tsx"></script>
            </body>
          </html>
          EOF

      - name: PHASE 3 - Rebuild Config (vite.config.ts)
        script: |
          echo "⚙️ Creating clean vite config..."
          cat <<EOF > vite.config.ts
          import { defineConfig } from 'vite'
          import react from '@vitejs/plugin-react'

          export default defineConfig({
            plugins: [react()],
            base: './', 
            build: { outDir: 'dist', emptyOutDir: true },
            server: { port: 3000 }
          })
          EOF

      - name: PHASE 4 - Rebuild Logic (src/App.tsx)
        script: |
          echo "🧠 Creating New AI Brain with Turbo Mode..."
          mkdir -p src
          
          # Create main.tsx to bootstrap React
          cat <<EOF > src/main.tsx
          import React from 'react'
          import ReactDOM from 'react-dom/client'
          import App from './App'
          import './index.css'

          ReactDOM.createRoot(document.getElementById('root')!).render(
            <React.StrictMode>
              <App />
            </React.StrictMode>,
          )
          EOF
          
          # Create CSS
          cat <<EOF > src/index.css
          body { margin: 0; font-family: sans-serif; background-color: #121212; color: white; }
          EOF

          # Create App.tsx (THE CHAT APP)
          cat <<EOF > src/App.tsx
          import { useState } from 'react';

          export default function App() {
            const [input, setInput] = useState("");
            const [messages, setMessages] = useState<{role: string, text: string}[]>([]);
            const [loading, setLoading] = useState(false);

            // TURBO MODE: 6 Keys
            const API_KEYS = [
              "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU", 
              "AIzaSyDBdShSHEOJwV5-fAn5ABJLfKG3RLffoUo", 
              "AIzaSyByhPkTsT2_zczOGGnHVJ2lLAhv14MNNxk", 
              "AIzaSyDLlrOBRykDoeIF7YUBsMf1G_rOAK2n53c", 
              "AIzaSyDbDzk2zEbJpDzLkyPC4a_z9WfMDfuYje0", 
              "AIzaSyAWfQ9NCe1x5BDR6MDu-tQYoTauqKbMljU"
            ];

            const sendMessage = async () => {
              if (!input.trim()) return;

              const newMessages = [...messages, { role: "user", text: input }];
              setMessages(newMessages);
              setInput("");
              setLoading(true);

              // 1. Pick Random Key
              const randomKey = API_KEYS[Math.floor(Math.random() * API_KEYS.length)];

              try {
                // 2. Direct Connection (No SDK)
                const response = await fetch(
                  "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=" + randomKey,
                  {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                      contents: [{ parts: [{ text: input }] }]
                    })
                  }
                );

                const data = await response.json();

                if (!response.ok) {
                  throw new Error(data.error?.message || "Google Blocked Request");
                }

                const botReply = data.candidates?.[0]?.content?.parts?.[0]?.text || "No reply from AI.";
                setMessages([...newMessages, { role: "model", text: botReply }]);

              } catch (error: any) {
                console.error("Error:", error);
                setMessages([...newMessages, { role: "model", text: "Error: " + error.message }]);
              } finally {
                setLoading(false);
              }
            };

            return (
              <div style={{ height: '100vh', display: 'flex', flexDirection: 'column' }}>
                <h2 style={{ textAlign: 'center', padding: 10, margin: 0, borderBottom: '1px solid #333' }}>SAQLAIN AI (Turbo)</h2>
                <div style={{ flex: 1, overflowY: 'auto', padding: 15 }}>
                  {messages.map((msg, index) => (
                    <div key={index} style={{ 
                      textAlign: msg.role === 'user' ? 'right' : 'left',
                      marginBottom: 10
                    }}>
                      <span style={{ 
                        backgroundColor: msg.role === 'user' ? '#007bff' : '#333',
                        padding: '10px 15px', 
                        borderRadius: 15,
                        display: 'inline-block',
                        maxWidth: '85%'
                      }}>
                        {msg.text}
                      </span>
                    </div>
                  ))}
                  {loading && <div style={{color: '#888'}}>Thinking...</div>}
                </div>
                <div style={{ padding: 10, display: 'flex', borderTop: '1px solid #333' }}>
                  <input 
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder="Type a message..."
                    style={{ flex: 1, padding: 12, borderRadius: 25, border: 'none', marginRight: 10 }}
                  />
                  <button onClick={sendMessage} style={{ padding: '10px 20px', borderRadius: 25, border: 'none', backgroundColor: '#007bff', color: 'white' }}>Send</button>
                </div>
              </div>
            );
          }
          EOF

      - name: Build Web Assets
        script: |
          npm run build

      - name: PHASE 5 - Perfect Manifest & Sync
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          echo "📝 Writing Clean AndroidManifest.xml..."
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET" />
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/AppTheme"
                  android:usesCleartextTraffic="true">
                  <activity
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
                      android:name="com.saqlainai.MainActivity"
                      android:label="@string/title_activity_main"
                      android:theme="@style/AppTheme.NoActionBarLaunch"
                      android:launchMode="singleTask"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  <provider
                      android:name="androidx.core.content.FileProvider"
                      android:authorities="\${applicationId}.fileprovider"
                      android:exported="false"
                      android:grantUriPermissions="true">
                      <meta-data
                          android:name="android.support.FILE_PROVIDER_PATHS"
                          android:resource="@xml/file_paths" />
                  </provider>
              </application>
          </manifest>
          EOF
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
