workflows:
  react-native-android:
    name: SAQLAIN AI - Direct Connect Final
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: STEP 1 - Create Raw Connection Service
        script: |
          echo "🔥 Creating Direct Connection Service..."
          mkdir -p services
          
          # We use a pure FETCH command. No libraries. No SDK bugs.
          cat <<EOF > services/geminiService.ts
          
          // YOUR CLEAN KEY
          const API_KEY = "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU";
          
          export async function sendMessageToGemini(message: string, history: any[]) {
            const url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=" + API_KEY;
            
            try {
              const response = await fetch(url, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ contents: [{ parts: [{ text: message }] }] })
              });

              const data = await response.json();

              if (!response.ok) {
                console.error("Google Error:", data);
                return "Error: " + (data.error?.message || "Google Rejected Connection");
              }
              return data.candidates[0].content.parts[0].text;
              
            } catch (error) {
              console.error("Network Error:", error);
              return "Error: Internet Connection Failed.";
            }
          }
          EOF

      - name: STEP 2 - Force App to Use New Service
        script: |
          echo "🔗 Linking App to Direct Connection..."
          
          # Find the file with the "Neural system failure" text
          TARGET_FILE=$(grep -r "Neural system failure" . | cut -d: -f1 | head -n 1)
          
          if [ -z "$TARGET_FILE" ]; then
             # Backup: Find file with sendMessage
             TARGET_FILE=$(grep -l "sendMessage" *.tsx 2>/dev/null | head -n 1)
          fi

          if [ ! -z "$TARGET_FILE" ]; then
             echo "Updating $TARGET_FILE..."
             
             # 1. Add the new import at the top
             sed -i '' "1s|^|import { sendMessageToGemini } from './services/geminiService';\n|" "$TARGET_FILE"
             
             # 2. FORCE the new function. We replace the old "sendMessage" call with ours.
             # This command looks for where you call the function and swaps it.
             sed -i '' "s/sendMessage(.*)/sendMessageToGemini(input, messages)/g" "$TARGET_FILE" || true
             
             echo "✅ App Logic Updated."
          else
             echo "⚠️ Could not auto-link. Build continuing with service file created."
          fi

      - name: Build Web Assets
        script: |
          npm run build

      - name: STEP 3 - Sync & Enforce Permissions
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          echo "🔓 Unlocking Android Internet Permissions..."
          
          # 1. Allow Cleartext (HTTP) traffic
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          # 2. Inject INTERNET PERMISSION (The missing link!)
          sed -i '' 's/<manifest/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android"/' android/app/src/main/AndroidManifest.xml
          sed -i '' '/<application/i \
          <uses-permission android:name="android.permission.INTERNET" /> \
          ' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
