workflows:
  react-native-android:
    name: SAQLAIN AI - Fail-Safe Fix
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          # GUARANTEE 1: Install the Brain
          npm install @google/generative-ai --save --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: FAIL-SAFE FIX - Inject API Key
        script: |
          echo "🎯 Scanning for the file with the error message..."
          
          # 1. Find the file that contains "Neural system failure"
          # We search recursively (-r) in all JS/TS files
          TARGET_FILE=$(grep -r --include="*.{js,jsx,ts,tsx}" "Neural system failure" . | cut -d: -f1 | head -n 1)
          
          # GUARANTEE 2: Don't proceed if we can't find the file
          if [ -z "$TARGET_FILE" ]; then
            echo "❌ CRITICAL ERROR: Could not find the file containing 'Neural system failure'."
            echo "Searching for App.tsx as a backup..."
            TARGET_FILE=$(find . -name "App.tsx" -o -name "index.tsx" | head -n 1)
          fi
          
          if [ -z "$TARGET_FILE" ]; then
             echo "❌ STILL FAILED: Could not find App.tsx or index.tsx. Exiting to prevent broken build."
             exit 1
          fi
          
          echo "✅ TARGET ACQUIRED: $TARGET_FILE"
          
          REAL_KEY="AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"
          
          # GUARANTEE 3: Inject Key (Method A: Constructor)
          # Replaces 'new GoogleGenerativeAI(...)' with 'new GoogleGenerativeAI("KEY")'
          sed -i '' "s|new GoogleGenerativeAI(.*)|new GoogleGenerativeAI(\"$REAL_KEY\")|g" "$TARGET_FILE"
          
          # GUARANTEE 4: Inject Key (Method B: Variable)
          # Replaces 'const API_KEY = ...' with 'const API_KEY = "KEY";'
          sed -i '' "s|const API_KEY = .*|const API_KEY = \"$REAL_KEY\";|g" "$TARGET_FILE"
          
          # GUARANTEE 5: Inject Key (Method C: Config Object)
          # Replaces 'apiKey: ...' with 'apiKey: "KEY",'
          sed -i '' "s|apiKey:.*|apiKey: \"$REAL_KEY\",|g" "$TARGET_FILE"
          
          echo "💉 API Key successfully injected into $TARGET_FILE"

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync Android & Icon
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          # GUARANTEE 6: Ensure Internet Permission
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
