workflows:
  android-apk-workflow:
    name: SAQLAIN AI APK Build
    max_build_duration: 120
    instance_type: linux
    environment:
      groups:
        - ai_credentials # This name must match exactly the group for your 6 API keys
    scripts:
      - name: Build Android APK
        script: | 
          chmod +x gradlew
          ./gradlew assembleDebug # This command creates the APK
    artifacts:
      - app/build/outputs/apk/*/.apk # This saves the APK for you to download
