workflows:
  react-native-android:
    name: SAQLAIN AI - Connection Fix
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @google/generative-ai --save --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: FIX SERVICE & CONNECTION
        script: |
          echo "🔧 Re-establishing Neural Link..."
          
          # 1. Create the Perfect Service File (Hardcoded Key)
          mkdir -p services
          cat <<EOF > services/geminiService.ts
          import { GoogleGenerativeAI } from "@google/generative-ai";

          const API_KEY = "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU";
          const genAI = new GoogleGenerativeAI(API_KEY);
          const model = genAI.getGenerativeModel({ model: "gemini-pro" });

          export async function sendMessageToGemini(message: string, history: any[]) {
            try {
              const chat = model.startChat({
                history: history.slice(-6).map(m => ({
                  role: m.role === 'user' ? 'user' : 'model',
                  parts: [{ text: m.text }]
                }))
              });
              const result = await chat.sendMessage(message);
              const response = await result.response;
              return response.text();
            } catch (error) {
              console.error("API Error:", error);
              return "Error: Neural Link Offline. Check Internet.";
            }
          }
          EOF
          
          echo "✅ Service Created."

          # 2. FORCE THE APP TO USE IT
          # This command searches for the file that has "sendMessage" logic and updates the import path
          # It assumes your main logic file is likely App.tsx or similar in the root
          
          echo "🔎 Updating Main App Logic..."
          
          # Find the file containing the chat logic (looking for 'sendMessage' or similar)
          TARGET_FILE=$(grep -l "sendMessage" *.tsx 2>/dev/null | head -n 1)
          
          if [ -z "$TARGET_FILE" ]; then
             echo "⚠️ Could not auto-detect App file. Trying standard names..."
             if [ -f "App.tsx" ]; then TARGET_FILE="App.tsx"; fi
             if [ -f "index.tsx" ]; then TARGET_FILE="index.tsx"; fi
          fi
          
          if [ ! -z "$TARGET_FILE" ]; then
             echo "🎯 Found logic in: $TARGET_FILE"
             
             # Replace the old import with the correct one pointing to our new service
             # We remove any existing import of geminiService and add the correct one at the top
             sed -i '' "/import.*geminiService/d" "$TARGET_FILE"
             sed -i '' "1s|^|import { sendMessageToGemini } from './services/geminiService';\n|" "$TARGET_FILE"
             
             # Replace the function call to ensure it uses our new function name
             # This finds whatever function was sending the message and swaps it to sendMessageToGemini
             # (This is a simplified replacement, assuming standard naming)
             sed -i '' "s/sendMessage(.message.)/sendMessageToGemini(input, messages)/g" "$TARGET_FILE" || true
             
             echo "✅ App Logic Linked to New Service."
          else
             echo "❌ Could not find main App file to link. Build will proceed with Service file created."
          fi

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync Android & Icon
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
