workflows:
  react-native-android:
    name: SAQLAIN AI APK Build
    max_build_duration: 120
    instance_type: linux_x86_64
    environment:
      groups:
        - ai_credentials # Pulls KEY1, KEY2, KEY3, KEY4, KEY5, and KEY6 from the UI
      vars:
        PACKAGE_NAME: "com.saqlainai" 
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Setup Environment Variables
        script: |
          # Creates a .env file with all 6 keys for the app to read
          echo "KEY1=$KEY1" > .env
          echo "KEY2=$KEY2" >> .env
          echo "KEY3=$KEY3" >> .env
          echo "KEY4=$KEY4" >> .env
          echo "KEY5=$KEY5" >> .env
          echo "KEY6=$KEY6" >> .env
      - name: Build Android APK
        script: | 
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
