workflows:
  react-native-android:
    name: SAQLAIN AI - Surgical Fix
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: SURGICAL OPERATION - Inject Logic Directly
        script: |
          echo "🏥 Starting Surgery..."
          
          # 1. FIND THE PATIENT (The file with the error)
          TARGET_FILE=$(grep -r --exclude-dir={node_modules,dist,android} "Neural system failure" . | cut -d: -f1 | head -n 1)
          
          if [ -z "$TARGET_FILE" ]; then
             echo "⚠️ Could not find specific error text. searching for App.tsx..."
             if [ -f "App.tsx" ]; then TARGET_FILE="App.tsx"; fi
          fi
          
          echo "✅ OPERATING ON: $TARGET_FILE"
          
          if [ ! -z "$TARGET_FILE" ]; then
             # 2. PROOF OF LIFE: Change the error message
             # If you see "Neural Link Reset" in the app, you know this script worked!
             sed -i '' "s/Neural system failure/Neural Link Reset - Retrying.../g" "$TARGET_FILE"
             
             # 3. INJECT THE KEY (Hardcode it everywhere)
             REAL_KEY="AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"
             sed -i '' "s/const API_KEY = .*/const API_KEY = \"$REAL_KEY\";/g" "$TARGET_FILE"
             sed -i '' "s/new GoogleGenerativeAI(.*)/new GoogleGenerativeAI(\"$REAL_KEY\")/g" "$TARGET_FILE"
             
             # 4. DIRECT INJECTION (Backup Plan)
             # If the app uses a variable for the key, we force-set it at the top of the file
             sed -i '' "1s|^|const FIXED_API_KEY = \"$REAL_KEY\";\n|" "$TARGET_FILE"
             
             echo "✅ Surgery Complete. Error message changed and Key Injected."
          else
             echo "❌ CRITICAL: Could not find the App file. Proceeding with clean manifest only."
          fi

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync & Write Perfect Manifest
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          echo "📝 Writing PERFECT AndroidManifest.xml..."
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET" />
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/AppTheme"
                  android:usesCleartextTraffic="true">
                  <activity
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
                      android:name="com.saqlainai.MainActivity"
                      android:label="@string/title_activity_main"
                      android:theme="@style/AppTheme.NoActionBarLaunch"
                      android:launchMode="singleTask"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  <provider
                      android:name="androidx.core.content.FileProvider"
                      android:authorities="\${applicationId}.fileprovider"
                      android:exported="false"
                      android:grantUriPermissions="true">
                      <meta-data
                          android:name="android.support.FILE_PROVIDER_PATHS"
                          android:resource="@xml/file_paths" />
                  </provider>
              </application>
          </manifest>
          EOF
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
