workflows:
  react-native-android:
    name: SAQLAIN AI - THE FINAL 1000 PERCENT SUCCESS
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      # FIX 1: Move to Java 21 globally. This stops the 'Version 65' crash immediately.
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
        # FIX 2: Kill the daemon and parallel tasks to ensure the JAR is created cleanly
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.vfs.watch=false"
        JAVA_TOOL_OPTIONS: "-Xmx6g"
      node: latest
    scripts:
      - name: STEP 1 - TOTAL SYSTEM PURGE
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
          export NODE_OPTIONS="--max-old-space-size=4096"
          # Physically wipe the corrupted JAR cache identified in your logs
          rm -rf ~/.gradle/caches/jars-9
          rm -rf ~/.gradle/caches/modules-2
          rm -rf android node_modules package-lock.json dist build capacitor.config.json
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor/splash-screen @capacitor/device --legacy-peer-deps

      - name: STEP 2 - PROJECT BUILD & AI SHIELD
        script: |
          # Use relative paths to fix Black Screen on ALL devices
          npm run build -- --base=./ 
          [ ! -d "dist" ] && mv build dist || true
          USER_API_KEY="$KEY1"
          cat <<EOF > interceptor.js
          <script>
          (function() {
            const KEYS = ["$USER_API_KEY", "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"];
            const oldFetch = window.fetch;
            window.fetch = async function(...args) {
              if (typeof args[0] === 'string' && args[0].includes('googleapis.com')) {
                const k = KEYS[0];
                let u = args[0].replace('gemini-pro', 'gemini-1.5-flash');
                u = u.includes('key=') ? u.replace(/key=[^&]*/, 'key='+k) : u + (u.includes('?') ? '&' : '?') + 'key=' + k;
                args[0] = u;
                args[1] = args[1] || {};
                args[1].headers = new Headers(args[1].headers || {});
                args[1].headers.delete('Origin');
                args[1].headers.delete('Referer');
              }
              return oldFetch(...args);
            };
          })();
          </script>
          EOF
          find dist -name "*.html" -exec sed -i '' -e '/<head>/r interceptor.js' {} +
          find dist -name "*.html" -exec sed -i '' 's|type="module"||g' {} +

      - name: STEP 3 - CLEAN PLATFORM REGENERATION
        script: |
          # Use 127.0.0.1 for maximum resolution compatibility
          echo "{ \"appId\": \"com.saqlainai\", \"appName\": \"SAQLAIN AI\", \"webDir\": \"dist\", \"server\": { \"hostname\": \"127.0.0.1\", \"androidScheme\": \"https\", \"cleartext\": true } }" > capacitor.config.json
          npx cap add android
          npx cap sync android
          mkdir -p android/app/src/main/assets/public
          cp -R dist/* android/app/src/main/assets/public/

      - name: STEP 4 - NATIVE APK HARDENING (V63)
        script: |
          MAIN_ACTIVITY=$(find android -name "MainActivity.java")
          sed -i '' 's/import com.getcapacitor.BridgeActivity;/import com.getcapacitor.BridgeActivity; import android.os.Bundle; import android.os.StrictMode; import android.webkit.WebSettings; import android.webkit.WebView; import android.os.Build;/g' "$MAIN_ACTIVITY"
          cat <<EOF > patch.txt
              @Override
              public void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  try {
                      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                          WebView.setWebContentsDebuggingEnabled(true);
                      }
                      StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().permitAll().build());
                      if (this.bridge != null && this.bridge.getWebView() != null) {
                          WebSettings s = this.bridge.getWebView().getSettings();
                          s.setMixedContentMode(0); 
                          s.setDomStorageEnabled(true);
                          s.setDatabaseEnabled(true);
                          s.setJavaScriptEnabled(true);
                          this.bridge.getWebView().setBackgroundColor(android.graphics.Color.WHITE);
                      }
                  } catch (Exception e) {}
              }
          EOF
          sed -i '' '/public void onCreate(Bundle savedInstanceState)/,/}/d' "$MAIN_ACTIVITY"
          sed -i '' -e '$i\
          ' patch.txt "$MAIN_ACTIVITY"
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '' 's|<manifest|<manifest xmlns:tools="http://schemas.android.com/tools"|g' "$MANIFEST"
          sed -i '' 's|<application|<application android:usesCleartextTraffic="true" tools:node="merge" tools:replace="android:usesCleartextTraffic,android:networkSecurityConfig" android:networkSecurityConfig="@xml/network_security_config"|g' "$MANIFEST"

      - name: STEP 5 - THE MASTER COMPILE (JAVA 21 ALIGNED)
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          # Update to Gradle 8.7 which supports Java 21 perfectly
          ./gradlew wrapper --gradle-version 8.7 --no-daemon
          ./gradlew clean --no-daemon
          # Force the compiler to be compatible with older Android phones
          ./gradlew assembleDebug --no-daemon --stacktrace -Pandroid.nonTransitiveRClass=false
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
