workflows:
  react-native-android:
    name: SAQLAIN AI Build (Auto-Fixer)
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\nKEY2=%s\nKEY3=%s\nKEY4=%s\nKEY5=%s\nKEY6=%s\n" \
          "$KEY1" "$KEY2" "$KEY3" "$KEY4" "$KEY5" "$KEY6" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: AUTO-FIX: Find Entry File & Update HTML
        script: |
          echo "Looking for entry file..."
          # Find the file (checks for main.tsx, main.jsx, main.js, index.tsx, etc.)
          ENTRY_FILE=$(find src -maxdepth 1 \( -name "main.tsx" -o -name "main.jsx" -o -name "main.js" -o -name "index.tsx" -o -name "index.jsx" -o -name "index.js" \) | head -n 1)
          
          if [ -z "$ENTRY_FILE" ]; then
            echo "CRITICAL ERROR: No entry file found in src folder!"
            ls -R src
            exit 1
          fi
          
          echo "FOUND ENTRY FILE: $ENTRY_FILE"
          
          # Automatically inject the correct filename into index.html
          # This replaces src="/src/..." with the real file we found
          sed -i '' "s|src=\"/src/.*\"|src=\"/$ENTRY_FILE\"|" index.html
          
          echo "Successfully updated index.html to use /$ENTRY_FILE"

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync Android & Icon
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
