workflows:
  react-native-android:
    name: SAQLAIN AI - Auto-Repair
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: AUTO-REPAIR - Rewrite Gemini Service
        script: |
          echo "🛠️ Creating fresh geminiService.ts..."
          
          # Ensure the folder exists
          mkdir -p services
          
          # Write the new, error-free code directly to the file
          cat <<EOF > services/geminiService.ts
          import { GoogleGenerativeAI } from "@google/generative-ai";

          // WE INJECT THE KEY DIRECTLY HERE
          const API_KEY = "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU";
          const genAI = new GoogleGenerativeAI(API_KEY);
          const model = genAI.getGenerativeModel({ model: "gemini-pro" });

          export async function sendMessageToGemini(message: string, history: any[]) {
            try {
              // Fixed: Removed the ': Content[]' type that was crashing the build
              const processedHistory = history.slice(-6).map((msg) => ({
                role: msg.role === 'user' ? 'user' : 'model',
                parts: [{ text: msg.text }] 
              }));

              const chat = model.startChat({
                history: processedHistory,
              });

              const result = await chat.sendMessage(message);
              const response = await result.response;
              return response.text();
              
            } catch (error) {
              console.error("Gemini API Error:", error);
              return "Error: Connection failed. Please check your internet.";
            }
          }
          EOF
          
          echo "✅ geminiService.ts has been repaired and API Key injected."

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync Android & Icon
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
