workflows:
  android-release:
    name: SAQLAIN AI Build
    # Ensure this name matches the folder name in your GitHub exactly
    working_directory: SAQLAIN-AI 
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - ai_credentials
      vars:
        PACKAGE_NAME: "com.saqlainai"
      flutter: stable
    scripts:
      - name: Setup Environment Variables
        script: |
          # Use the absolute build directory path to avoid 'not found' errors
          cd $FCI_BUILD_DIR/SAQLAIN-AI
          echo "KEY1=$KEY1" > .env
          echo "KEY2=$KEY2" >> .env
          echo "KEY3=$KEY3" >> .env
          echo "KEY4=$KEY4" >> .env
          echo "KEY5=$KEY5" >> .env
          echo "KEY6=$KEY6" >> .env
      - name: Get dependencies
        script: |
          cd $FCI_BUILD_DIR/SAQLAIN-AI
          flutter pub get
      - name: Build Android APK
        script: |
          cd $FCI_BUILD_DIR/SAQLAIN-AI
          flutter build apk --release
    artifacts:
      - SAQLAIN-AI/build/app/outputs/flutter-apk/*.apk
