workflows:
  react-native-android:
    name: SAQLAIN AI - Total Turbo Replacement
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps
          # Ensure React is installed
          npm install react react-dom --legacy-peer-deps
          npm install @vitejs/plugin-react --save-dev --legacy-peer-deps

      - name: NUCLEAR OPTION - Overwrite App.tsx with Turbo Mode
        script: |
          echo "☢️ STARTING TOTAL REPLACEMENT (TURBO EDITION)..."
          
          mkdir -p src
          
          # We write a COMPLETE Chat App with 6-KEY TURBO LOGIC
          cat <<EOF > src/App.tsx
          import { useState } from 'react';
          import './App.css'; 

          export default function App() {
            const [input, setInput] = useState("");
            const [messages, setMessages] = useState<{role: string, text: string}[]>([]);
            const [loading, setLoading] = useState(false);

            // TURBO MODE: All 6 Keys
            const API_KEYS = [
              "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU", 
              "AIzaSyDBdShSHEOJwV5-fAn5ABJLfKG3RLffoUo", 
              "AIzaSyByhPkTsT2_zczOGGnHVJ2lLAhv14MNNxk", 
              "AIzaSyDLlrOBRykDoeIF7YUBsMf1G_rOAK2n53c", 
              "AIzaSyDbDzk2zEbJpDzLkyPC4a_z9WfMDfuYje0", 
              "AIzaSyAWfQ9NCe1x5BDR6MDu-tQYoTauqKbMljU"
            ];

            const sendMessage = async () => {
              if (!input.trim()) return;

              const newMessages = [...messages, { role: "user", text: input }];
              setMessages(newMessages);
              setInput("");
              setLoading(true);

              // 🎲 PICK A RANDOM KEY (Safe & Fast)
              const randomKey = API_KEYS[Math.floor(Math.random() * API_KEYS.length)];

              try {
                // DIRECT CONNECTION
                const response = await fetch(
                  "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=" + randomKey,
                  {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                      contents: [{ parts: [{ text: input }] }]
                    })
                  }
                );

                const data = await response.json();

                if (!response.ok) {
                  throw new Error(data.error?.message || "Google Blocked Request");
                }

                const botReply = data.candidates[0].content.parts[0].text;
                setMessages([...newMessages, { role: "model", text: botReply }]);

              } catch (error: any) {
                console.error("Error:", error);
                setMessages([...newMessages, { role: "model", text: "Error: " + error.message }]);
              } finally {
                setLoading(false);
              }
            };

            return (
              <div style={{ padding: 20, height: '100vh', display: 'flex', flexDirection: 'column', backgroundColor: '#121212', color: 'white' }}>
                <h2 style={{ textAlign: 'center' }}>SAQLAIN AI</h2>
                <div style={{ flex: 1, overflowY: 'auto', marginBottom: 20 }}>
                  {messages.map((msg, index) => (
                    <div key={index} style={{ 
                      textAlign: msg.role === 'user' ? 'right' : 'left',
                      margin: '10px 0' 
                    }}>
                      <span style={{ 
                        backgroundColor: msg.role === 'user' ? '#007bff' : '#333',
                        padding: '10px 15px', 
                        borderRadius: 15,
                        display: 'inline-block',
                        maxWidth: '80%'
                      }}>
                        {msg.text}
                      </span>
                    </div>
                  ))}
                  {loading && <div>Thinking...</div>}
                </div>
                <div style={{ display: 'flex' }}>
                  <input 
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
                    placeholder="Type a message..."
                    style={{ flex: 1, padding: 15, borderRadius: 25, border: 'none', marginRight: 10 }}
                  />
                  <button onClick={sendMessage} style={{ padding: '15px 25px', borderRadius: 25, border: 'none', backgroundColor: '#007bff', color: 'white' }}>Send</button>
                </div>
              </div>
            );
          }
          EOF
          
          echo "✅ App.tsx replaced with TURBO MODE."

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync & Write Perfect Manifest
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          echo "📝 Writing PERFECT AndroidManifest.xml..."
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET" />
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/AppTheme"
                  android:usesCleartextTraffic="true">
                  <activity
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
                      android:name="com.saqlainai.MainActivity"
                      android:label="@string/title_activity_main"
                      android:theme="@style/AppTheme.NoActionBarLaunch"
                      android:launchMode="singleTask"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  <provider
                      android:name="androidx.core.content.FileProvider"
                      android:authorities="\${applicationId}.fileprovider"
                      android:exported="false"
                      android:grantUriPermissions="true">
                      <meta-data
                          android:name="android.support.FILE_PROVIDER_PATHS"
                          android:resource="@xml/file_paths" />
                  </provider>
              </application>
          </manifest>
          EOF
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
