workflows:
  react-native-android:
    name: SAQLAIN AI - API Key Fix
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: SURGEON FIX - Inject API Key Directly into Code
        script: |
          echo "Starting Open-Heart Surgery on the Code..."
          
          # Your Real API Key
          REAL_KEY="AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"
          
          # 1. Replaces process.env.GEMINI_API_KEY
          LC_ALL=C find src -type f -exec sed -i '' "s/process.env.GEMINI_API_KEY/\"$REAL_KEY\"/g" {} +
          
          # 2. Replaces import.meta.env.VITE_GEMINI_API_KEY
          LC_ALL=C find src -type f -exec sed -i '' "s/import.meta.env.VITE_GEMINI_API_KEY/\"$REAL_KEY\"/g" {} +
          
          # 3. Replaces generic VITE_API_KEY
          LC_ALL=C find src -type f -exec sed -i '' "s/import.meta.env.VITE_API_KEY/\"$REAL_KEY\"/g" {} +
          
          # 4. Replaces REACT_APP_GEMINI_API_KEY
          LC_ALL=C find src -type f -exec sed -i '' "s/process.env.REACT_APP_GEMINI_API_KEY/\"$REAL_KEY\"/g" {} +
          
          # 5. Replaces plain GEMINI_API_KEY
          LC_ALL=C find src -type f -exec sed -i '' "s/import.meta.env.GEMINI_API_KEY/\"$REAL_KEY\"/g" {} +
          
          echo "Surgery Complete. API Key has been physically implanted."

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync Android & Icon
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
