workflows:
  react-native-android:
    name: SAQLAIN AI - Final Fix
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: SURGEON FIX - Inject API Key (Root Scan)
        script: |
          echo "🔎 Scanning ROOT folder for code..."
          
          # Your Real API Key
          REAL_KEY="AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"
          
          # 1. Force-feed the key into the Google AI setup function
          # We search the current folder (.) but ignore junk folders
          grep -rl --exclude-dir={node_modules,android,dist,.git} "new GoogleGenerativeAI" . | xargs sed -i '' "s|new GoogleGenerativeAI(.*)|new GoogleGenerativeAI(\"$REAL_KEY\")|g"
          
          # 2. Force-feed the key into any 'apiKey:' fields
          grep -rl --exclude-dir={node_modules,android,dist,.git} "apiKey:" . | xargs sed -i '' "s|apiKey:.*|apiKey: \"$REAL_KEY\",|g"
          
          # 3. Replace any process.env variables with the real key
          grep -rl --exclude-dir={node_modules,android,dist,.git} "process.env.GEMINI_API_KEY" . | xargs sed -i '' "s|process.env.GEMINI_API_KEY|\"$REAL_KEY\"|g"
          
          # 4. Replace any VITE variables with the real key
          grep -rl --exclude-dir={node_modules,android,dist,.git} "import.meta.env.VITE_GEMINI_API_KEY" . | xargs sed -i '' "s|import.meta.env.VITE_GEMINI_API_KEY|\"$REAL_KEY\"|g"

          echo "✅ Key Injection Complete."

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync Android & Icon
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
