workflows:
  android-release:
    name: SAQLAIN AI Build
    # This ensures it runs in the root where your pubspec.yaml is
    working_directory: . 
    instance_type: mac_mini_m1 
    max_build_duration: 60
    environment:
      groups:
        - ai_credentials # IMPORTANT: Check that your UI group name is EXACTLY this
      vars:
        PACKAGE_NAME: "com.saqlainai"
      flutter: stable
    scripts:
      - name: Setup Environment Variables
        script: |
          # This creates the .env file even if the keys are empty to prevent failure
          touch .env
          printf "KEY1=%s\nKEY2=%s\nKEY3=%s\nKEY4=%s\nKEY5=%s\nKEY6=%s\n" \
          "$KEY1" "$KEY2" "$KEY3" "$KEY4" "$KEY5" "$KEY6" > .env
          echo "Environment file created successfully."
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
