workflows:
  react-native-android:
    name: SAQLAIN AI - Clean Manifest Fix
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: STEP 1 - Create Direct Connection Service
        script: |
          echo "🔥 Creating Direct Connection Service..."
          mkdir -p services
          
          # Clean Key - Direct Connect Mode
          cat <<EOF > services/geminiService.ts
          const API_KEY = "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU";
          
          export async function sendMessageToGemini(message: string, history: any[]) {
            const url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=" + API_KEY;
            
            try {
              const response = await fetch(url, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ contents: [{ parts: [{ text: message }] }] })
              });

              const data = await response.json();

              if (!response.ok) {
                console.error("Google Error:", data);
                return "Error: " + (data.error?.message || "Google Rejected Connection");
              }
              return data.candidates[0].content.parts[0].text;
              
            } catch (error) {
              console.error("Network Error:", error);
              return "Error: Internet Connection Failed.";
            }
          }
          EOF

      - name: STEP 2 - Force App to Use New Service
        script: |
          echo "🔗 Linking App to Direct Connection..."
          
          # Find target file (ignoring node_modules)
          TARGET_FILE=$(grep -r --exclude-dir={node_modules,dist,android} "sendMessage" . | cut -d: -f1 | head -n 1)
          
          if [ -z "$TARGET_FILE" ]; then
             if [ -f "App.tsx" ]; then TARGET_FILE="App.tsx"; fi
          fi

          if [ ! -z "$TARGET_FILE" ]; then
             echo "Updating $TARGET_FILE..."
             # Add import
             sed -i '' "1s|^|import { sendMessageToGemini } from './services/geminiService';\n|" "$TARGET_FILE"
             # Swap function
             sed -i '' "s/sendMessage(.*)/sendMessageToGemini(input, messages)/g" "$TARGET_FILE" || true
             echo "✅ App Logic Updated."
          fi

      - name: Build Web Assets
        script: |
          npm run build

      - name: STEP 3 - Sync & Write Perfect Manifest
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          echo "📝 Writing PERFECT AndroidManifest.xml..."
          
          # We overwrite the broken file with a 100% correct one
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
          
              <uses-permission android:name="android.permission.INTERNET" />
          
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/AppTheme"
                  android:usesCleartextTraffic="true">
          
                  <activity
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
                      android:name="com.saqlainai.MainActivity"
                      android:label="@string/title_activity_main"
                      android:theme="@style/AppTheme.NoActionBarLaunch"
                      android:launchMode="singleTask"
                      android:exported="true">
          
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
          
                  </activity>
          
                  <provider
                      android:name="androidx.core.content.FileProvider"
                      android:authorities="\${applicationId}.fileprovider"
                      android:exported="false"
                      android:grantUriPermissions="true">
                      <meta-data
                          android:name="android.support.FILE_PROVIDER_PATHS"
                          android:resource="@xml/file_paths" />
                  </provider>
              </application>
          </manifest>
          EOF
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
