workflows:
  react-native-android:
    name: SAQLAIN AI - THE UNIVERSAL MASTER
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
        JAVA_TOOL_OPTIONS: "-Xmx6g -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
      node: latest
    scripts:
      - name: STEP 1 - NUCLEAR RESET
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
          rm -rf ~/.gradle/caches
          rm -rf node_modules package-lock.json android dist build capacitor.config.json
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor/splash-screen @capacitor/device --legacy-peer-deps

      - name: STEP 2 - VITE UNIVERSAL PATH ENGINE
        script: |
          npm run build -- --base=./ 
          [ ! -d "dist" ] && mv build dist || true
          USER_API_KEY="$KEY1"
          cat <<EOF > interceptor.js
          <script>
          (function() {
            const KEYS = ["$USER_API_KEY", "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"];
            const oldFetch = window.fetch;
            window.fetch = async function(...args) {
              if (typeof args[0] === 'string' && args[0].includes('googleapis.com')) {
                const k = KEYS[0];
                let u = args[0].replace('gemini-pro', 'gemini-1.5-flash');
                u = u.includes('key=') ? u.replace(/key=[^&]*/, 'key='+k) : u + (u.includes('?') ? '&' : '?') + 'key=' + k;
                args[0] = u;
                args[1] = args[1] || {};
                args[1].headers = new Headers(args[1].headers || {});
                args[1].headers.delete('Origin');
                args[1].headers.delete('Referer');
              }
              return oldFetch(...args);
            };
          })();
          </script>
          EOF
          find dist -name "*.html" -exec sed -i '' -e '/<head>/r interceptor.js' {} +
          find dist -name "*.html" -exec sed -i '' 's|type="module"||g' {} +
          find dist -name "*.html" -exec sed -i '' 's|crossorigin||g' {} +

      - name: STEP 3 - EDGE-TO-EDGE & CLEARTEXT CONFIG
        script: |
          cat <<EOF > capacitor.config.json
          {
            "appId": "com.saqlainai",
            "appName": "SAQLAIN AI",
            "webDir": "dist",
            "server": { "hostname": "127.0.0.1", "androidScheme": "https", "cleartext": true },
            "android": { "adjustMarginsForEdgeToEdge": "disable" }
          }
          EOF
          npx cap add android
          cd android && ./gradlew wrapper --gradle-version 8.7 --distribution-type all && cd ..
          npx cap sync android
          cp -R dist/* android/app/src/main/assets/public/

      - name: STEP 4 - NATIVE ATOMIC STRIKE (LEGACY & 16KB WELD)
        script: |
          sleep 3
          MAIN_ACTIVITY=$(find android/app/src/main/java -name "MainActivity.java")
          sed -i '' 's/import com.getcapacitor.BridgeActivity;/import com.getcapacitor.BridgeActivity; import android.os.Bundle; import android.os.StrictMode; import android.webkit.WebSettings; import android.webkit.WebView; import android.os.Build;/g' "$MAIN_ACTIVITY"
          cat <<EOF > patch.txt
              @Override
              public void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  try {
                      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                          WebView.setWebContentsDebuggingEnabled(true);
                      }
                      StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().permitAll().build());
                      if (this.bridge != null && this.bridge.getWebView() != null) {
                          WebSettings s = this.bridge.getWebView().getSettings();
                          s.setMixedContentMode(0); 
                          s.setDomStorageEnabled(true);
                          s.setDatabaseEnabled(true);
                          s.setJavaScriptEnabled(true);
                          this.bridge.getWebView().setBackgroundColor(android.graphics.Color.WHITE);
                      }
                  } catch (Exception e) {}
              }
          EOF
          sync
          sed -i '' '/public void onCreate(Bundle savedInstanceState)/,/}/d' "$MAIN_ACTIVITY"
          sed -i '' -e '$i\
          ' patch.txt "$MAIN_ACTIVITY"
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '' 's|<manifest|<manifest xmlns:tools="http://schemas.android.com/tools"|g' "$MANIFEST"
          sed -i '' 's|<application|<application android:usesCleartextTraffic="true" tools:node="merge" tools:replace="android:usesCleartextTraffic,android:networkSecurityConfig" android:networkSecurityConfig="@xml/network_security_config"|g' "$MANIFEST"

      - name: STEP 5 - THE CLEAN COMPILE (16KB PAGE-ALIGNED)
        script: |
          export JAVA_HOME=$JAVA_HOME_17
          cd android
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          ./gradlew clean --no-daemon
          ./gradlew assembleDebug --no-daemon --stacktrace -Pandroid.nonTransitiveRClass=false
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
