workflows:
  react-native-android:
    name: SAQLAIN AI APK Build
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\nKEY2=%s\nKEY3=%s\nKEY4=%s\nKEY5=%s\nKEY6=%s\n" \
          "$KEY1" "$KEY2" "$KEY3" "$KEY4" "$KEY5" "$KEY6" > .env
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android
      - name: Build Web Assets
        script: |
          npm run build
      - name: Initialize Android Platform
        script: |
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist || true
          npx cap add android || true
          npx cap sync android
      - name: Build Android Debug APK
        script: |
          # Changed 'assembleRelease' to 'assembleDebug' for easy installation
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      # This will find the 'app-debug.apk' which your phone will accept
      - android/app/build/outputs/apk/debug/*.apk
