workflows:
  react-native-android:
    name: SAQLAIN AI APK Build
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - ai_credentials # Ensure KEY1-KEY6 are in this group in Codemagic UI
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\nKEY2=%s\nKEY3=%s\nKEY4=%s\nKEY5=%s\nKEY6=%s\n" \
          "$KEY1" "$KEY2" "$KEY3" "$KEY4" "$KEY5" "$KEY6" > .env
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          # THE FIX: This command checks if 'android' exists, then builds
          if [ -d "android" ]; then
            cd android && ./gradlew assembleRelease
          else
            echo "ERROR: 'android' folder not found. Check your GitHub files!"
            exit 1
          fi
    artifacts:
      - "**/release/*.apk"
