workflows:
  android-release:
    name: SAQLAIN AI Build
    # This line is the fix: it tells the build to look inside the subfolder
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      flutter: stable
    scripts:
      - name: Setup Environment Variables
        script: |
          # This part is already working for you
          echo "KEY1=$KEY1" > .env
          echo "KEY2=$KEY2" >> .env
          echo "KEY3=$KEY3" >> .env
          echo "KEY4=$KEY4" >> .env
          echo "KEY5=$KEY5" >> .env
          echo "KEY6=$KEY6" >> .env
      - name: Get dependencies
        script: |
          # The fix: Ensures it runs 'flutter pub get' in the correct folder
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
