workflows:
  react-native-android:
    name: SAQLAIN AI Build (Detective Mode)
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\nKEY2=%s\nKEY3=%s\nKEY4=%s\nKEY5=%s\nKEY6=%s\n" \
          "$KEY1" "$KEY2" "$KEY3" "$KEY4" "$KEY5" "$KEY6" > .env
      
      - name: DETECT FILE STRUCTURE (Crucial Step)
        script: |
          echo "================ FILE LIST START ================"
          find . -maxdepth 3 -not -path '/.'
          echo "================ FILE LIST END ================"
          
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps
          
      - name: Build Web Assets
        script: |
          # Try to build. If it fails, we will check the 'DETECT FILE' log above.
          npm run build
          
      - name: Sync Android
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android
          
      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
