workflows:
  react-native-android:
    name: SAQLAIN AI - Brute Force Fix
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 21
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: Setup Environment Variables
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
      
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/assets --save-dev --legacy-peer-deps

      - name: BRUTE FORCE - Inject API Key
        script: |
          echo "🔎 Scanning files..."
          
          # Your Real Key
          REAL_KEY="AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"
          
          # Strategy 1: Find 'new GoogleGenerativeAI(...)' and force the key
          # This works if you are using the standard SDK
          grep -rl "new GoogleGenerativeAI" src | xargs sed -i '' "s|new GoogleGenerativeAI(.*)|new GoogleGenerativeAI(\"$REAL_KEY\")|g"
          
          # Strategy 2: Find 'apiKey: ...' (Common in new SDKs) and force the key
          # We are careful to only target lines with 'apiKey:' inside src
          grep -rl "apiKey:" src | xargs sed -i '' "s|apiKey:.*|apiKey: \"$REAL_KEY\",|g"
          
          # Strategy 3: Find common placeholders and destroy them
          grep -rl "YOUR_API_KEY" src | xargs sed -i '' "s|YOUR_API_KEY|$REAL_KEY|g"
          
          echo "✅ Injection attempts complete."
          
          # DEBUG: List files so we know where the code lives if this fails
          echo "📂 File Structure:"
          find src -maxdepth 3

      - name: Build Web Assets
        script: |
          npm run build

      - name: Sync Android & Icon
        script: |
          rm -rf android
          npx cap init "SAQLAIN AI" "com.saqlainai" --web-dir dist
          npx cap add android
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          if [ -f "assets/icon.png" ]; then
            npx capacitor-assets generate android
          fi
          
          npx cap sync android

      - name: Build Android Debug APK
        script: |
          export JAVA_HOME=$JAVA_HOME_21
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
