workflows:
  react-native-android:
    name: SAQLAIN AI - THE FINAL 1000 PERCENT SUCCESS
    working_directory: . 
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      groups:
        - ai_credentials 
      vars:
        PACKAGE_NAME: "com.saqlainai"
      node: latest
    scripts:
      - name: STEP 1 - NUCLEAR RESET
        script: |
          printf "KEY1=%s\n" "$KEY1" > .env
          export NODE_OPTIONS="--max-old-space-size=4096"
          rm -rf node_modules package-lock.json android dist build capacitor.config.json local.properties
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor/splash-screen @capacitor/device --legacy-peer-deps

      - name: STEP 2 - FORCE-RELATIVE PATHS & API INTERCEPTOR
        script: |
          # 1. Force Vite to build with relative paths (Total Black Screen Killer)
          npm run build -- --base=./ 
          [ ! -d "dist" ] && mv build dist || true
          
          # 2. Hardened Interceptor (Fixes API & Neural Link failures)
          USER_API_KEY="$KEY1"
          cat <<EOF > interceptor.js
          <script>
          (function() {
            window.SAQLAIN_READY = true;
            const KEYS = ["$USER_API_KEY", "AIzaSyDsWqaqeyFFdAs6rXA8xOBZpwh_uhc4ZXU"];
            const oldFetch = window.fetch;
            window.fetch = async function(...args) {
              if (typeof args[0] === 'string' && args[0].includes('googleapis.com')) {
                const k = KEYS[0];
                let u = args[0].replace('gemini-pro', 'gemini-1.5-flash');
                u = u.includes('key=') ? u.replace(/key=[^&]*/, 'key='+k) : u + (u.includes('?') ? '&' : '?') + 'key=' + k;
                args[0] = u;
                args[1] = args[1] || {};
                args[1].headers = new Headers(args[1].headers || {});
                args[1].headers.delete('Origin');
                args[1].headers.delete('Referer');
              }
              return oldFetch(...args);
            };
            // Force hide splash screen to prevent black screen hang
            document.addEventListener('DOMContentLoaded', () => {
               setTimeout(() => { if(window.Capacitor) window.Capacitor.Plugins.SplashScreen.hide(); }, 1000);
            });
          })();
          </script>
          EOF
          find dist -name "*.html" -exec sed -i '' -e '/<head>/r interceptor.js' {} +
          # Strip module types to support older Android WebViews
          find dist -name "*.html" -exec sed -i '' 's|type="module"||g' {} +
          find dist -name "*.html" -exec sed -i '' 's|crossorigin||g' {} +

      - name: STEP 3 - NATIVE CONFIG & ANDROID 15 EDGE-TO-EDGE
        script: |
          # Use 127.0.0.1 for maximum device compatibility
          cat <<EOF > capacitor.config.json
          {
            "appId": "com.saqlainai",
            "appName": "SAQLAIN AI",
            "webDir": "dist",
            "server": {
              "hostname": "127.0.0.1",
              "androidScheme": "https",
              "cleartext": true
            },
            "plugins": {
              "SplashScreen": { "launchShowDuration": 0 }
            }
          }
          EOF
          npx cap add android
          mkdir -p android/app/src/main/res/xml
          cat <<EOF > android/app/src/main/res/xml/network_security_config.xml
          <?xml version="1.0" encoding="utf-8"?><network-security-config><base-config cleartextTrafficPermitted="true"><trust-anchors><certificates src="system" /><certificates src="user" /></trust-anchors></base-config></network-security-config>
          EOF
          npx cap sync android
          cp -R dist/* android/app/src/main/assets/public/

      - name: STEP 4 - NATIVE ATOMIC STRIKE (ANDROID 15 COMPATIBILITY)
        script: |
          sleep 3
          MAIN_ACTIVITY=$(find android/app/src/main/java -name "MainActivity.java")
          sed -i '' 's/import com.getcapacitor.BridgeActivity;/import com.getcapacitor.BridgeActivity; import android.os.Bundle; import android.os.StrictMode; import android.webkit.WebSettings; import android.webkit.WebView; import android.os.Build;/g' "$MAIN_ACTIVITY"
          cat <<EOF > patch.txt
              @Override
              public void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  try {
                      // Enable remote debugging for edge://inspect
                      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                          WebView.setWebContentsDebuggingEnabled(true);
                      }
                      StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().permitAll().build());
                      if (this.bridge != null && this.bridge.getWebView() != null) {
                          WebSettings s = this.bridge.getWebView().getSettings();
                          s.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
                          s.setDomStorageEnabled(true);
                          s.setDatabaseEnabled(true);
                          s.setJavaScriptEnabled(true);
                          this.bridge.getWebView().setBackgroundColor(android.graphics.Color.WHITE);
                      }
                  } catch (Exception e) {}
              }
          EOF
          sync
          sed -i '' '/public void onCreate(Bundle savedInstanceState)/,/}/d' "$MAIN_ACTIVITY"
          sed -i '' -e '$i\
          ' patch.txt "$MAIN_ACTIVITY"
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '' 's|<manifest|<manifest xmlns:tools="http://schemas.android.com/tools"|g' "$MANIFEST"
          sed -i '' 's|<application|<application android:usesCleartextTraffic="true" tools:node="merge" tools:replace="android:usesCleartextTraffic,android:networkSecurityConfig" android:networkSecurityConfig="@xml/network_security_config"|g' "$MANIFEST"

      - name: STEP 5 - THE CLEAN COMPILE
        script: |
          export JAVA_HOME=$JAVA_HOME_17
          cd android
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon --rerun-tasks -Porg.gradle.java.home=$JAVA_HOME_17 -Pandroid.nonTransitiveRClass=false
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
